# This is a basic workflow to help you get started with Actions

name: CI

    # Steps represent a sequence of tasks that will be executed as part of the job
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Run markdown lint
        run: |
          npm install remark-cli remark-preset-lint-consistent
          npx remark . --use remark-preset-lint-consistent --frail

      - uses: actions/upload-artifact@v3
        with:
          name: remark-lint-report
          path: public/
